/**
 * app.js — DOM orchestrator. Calling direction is one-way:
 * app.js -> {storage, importer, exporter, parser}. This module owns all
 * DOM access; the other four modules never touch the DOM or each other.
 */
(function () {
  "use strict";

  const S = window.LegalStorage;
  const I = window.LegalImporter;
  const E = window.LegalExporter;

  const IS_RESEARCHER = new URLSearchParams(window.location.search).get("researcher") === "true";

  const CORRECTNESS_LABELS = { 1: "Completely Incorrect", 2: "Mostly Incorrect", 3: "Partially Correct", 4: "Mostly Correct", 5: "Fully Correct" };
  const CONFIDENCE_LABELS = { 1: "Very Low", 2: "Low", 3: "Moderate", 4: "High", 5: "Very High" };

  // Original per-Act PDFs generated by the system's own pipeline
  // (V6.5/LawAI/media/ScenarioExtraction/Scenario N/*.pdf), copied into
  // data/scenario_pdfs/scenario-N/ so they can be offered as a direct
  // download alongside the in-app markdown rendering. Only meaningful for
  // scenario data that actually came bundled with matching PDFs — if a
  // researcher/admin publishes different scenario data, these links may
  // 404, which is an acceptable edge case for this bonus feature.
  const ACT_PDF_FILENAMES = {
    "Information Technology (IT) Act, 2000": "ITAct.pdf",
    "Bharatiya Nyaya Sanhita (BNS), 2023": "BNSAct.pdf",
    "Bharatiya Sakshya Adhiniyam (BSA), 2023": "BSA.pdf",
    "Digital Personal Data Protection Act (DPDP), 2023": "DPDPAct.pdf",
  };

  function scenarioPdfUrl(scenarioIndex, filename) {
    return `data/scenario_pdfs/scenario-${scenarioIndex}/${filename}`;
  }

  function renderActPdfLink(scenarioIndex, actName) {
    const filename = ACT_PDF_FILENAMES[actName];
    if (!filename) return "";
    return `<a class="btn-text" href="${escapeAttr(scenarioPdfUrl(scenarioIndex, filename))}" target="_blank" rel="noopener">Download Original PDF ↓</a>`;
  }

  /** @type {object} */
  let state = null;
  // Holds a merged-but-not-yet-committed scenario array while the
  // researcher-import screen is open, before "Start Review" is clicked.
  let pendingResearcherScenarios = null;
  // Ephemeral, never persisted: which "View System Explanation" panels are
  // open. Every state-changing click triggers a full renderActCards()
  // regeneration of the DOM, which would otherwise re-collapse an
  // already-opened panel — tracked here so it survives across re-renders.
  const openExplanationIds = new Set();

  // ---------------------------------------------------------------------
  // Boot
  // ---------------------------------------------------------------------
  document.addEventListener("DOMContentLoaded", boot);

  async function boot() {
    populateEntryFormOptions();
    wireEntryForm();
    wireResumeSession();
    wireDropzone("fallback-dropzone", "fallback-file-input", "fallback-choose-btn", (files) =>
      handleFallbackFiles(files)
    );
    wireDropzone("researcher-dropzone", "researcher-file-input", "researcher-choose-btn", (files) =>
      handleResearcherFiles(files)
    );
    wireStaticButtons();

    if (IS_RESEARCHER) {
      showScreen("researcher-import");
      return;
    }

    const restored = S.loadState();
    state = restored || S.createInitialState();
    await routeFromState(true);
  }

  // Decides which screen to show for the current `state` — shared by
  // normal boot (from localStorage) and by "Resume on this device" after
  // a cross-device session is pulled in from Supabase (see
  // wireResumeSession below), so both paths land in the same place.
  async function routeFromState(isBootRestore) {
    if (state.submitted_at) {
      showScreen("completion");
      renderCompletionScreen();
      showPostSubmitPanel();
      return;
    }

    if (state.reviewer.entry_completed && state.scenario_source.loaded && state.scenarios.length > 0) {
      showScreen("review");
      renderReviewScreen(isBootRestore);
      return;
    }

    if (!state.reviewer.entry_completed) {
      showScreen("lawyer-entry");
      return;
    }

    // Entry completed but no data yet loaded.
    await proceedToDataLoad();
  }

  // ---------------------------------------------------------------------
  // Persistence: always saves to localStorage (same-device autosave);
  // additionally, debounced and separately, syncs to Supabase's
  // review_sessions table (if configured and the reviewer's email is
  // known) so the same in-progress review can resume on another device.
  // The remote sync is deliberately on its own longer debounce — it's a
  // network call, not a local write, and must never block or slow down
  // the local-save path that every click already depends on.
  // ---------------------------------------------------------------------
  // Returns a promise so callers that need to know the remote sync
  // actually landed before telling the lawyer "safe to close this tab"
  // (see review-save-draft-btn below) can await it; callers that don't
  // care (most click handlers) simply don't await it, which is fine.
  function persistState(immediate) {
    if (immediate) S.saveStateNow(state);
    else S.saveState(state);
    return syncSessionRemote(immediate);
  }

  let _remoteSyncTimer = null;
  function syncSessionRemote(immediate) {
    if (!window.LegalSupabase || !window.LegalSupabase.isConfigured()) return Promise.resolve({ ok: true, skipped: true });
    if (!state || !state.reviewer.email || state.submitted_at) return Promise.resolve({ ok: true, skipped: true });
    if (_remoteSyncTimer) {
      clearTimeout(_remoteSyncTimer);
      _remoteSyncTimer = null;
    }
    const doSync = () =>
      window.LegalSupabase.saveSessionRemote(state.reviewer.email, state).then((result) => {
        if (!result.ok) console.warn("remote session sync failed:", result.error);
        return result;
      });
    if (immediate) return doSync();
    return new Promise((resolve) => {
      _remoteSyncTimer = setTimeout(() => resolve(doSync()), 1500);
    });
  }

  // ---------------------------------------------------------------------
  // Screen switching
  // ---------------------------------------------------------------------
  function showScreen(name) {
    document.querySelectorAll("[data-screen]").forEach((el) => {
      el.classList.toggle("active", el.getAttribute("data-screen") === name);
    });
  }

  // ---------------------------------------------------------------------
  // Lawyer entry screen
  // ---------------------------------------------------------------------
  function populateEntryFormOptions() {
    const expSelect = document.getElementById("entry-experience");
    for (const opt of S.EXPERIENCE_OPTIONS) {
      const o = document.createElement("option");
      o.value = opt;
      o.textContent = opt;
      expSelect.appendChild(o);
    }
    const grid = document.getElementById("entry-practice-areas");
    grid.innerHTML = S.PRACTICE_AREA_OPTIONS.map(
      (area, i) => `
      <label class="checkbox-row">
        <input type="checkbox" name="practice_area" value="${escapeHtml(area)}" id="practice-area-${i}" />
        ${escapeHtml(area)}
      </label>`
    ).join("");
  }

  function wireEntryForm() {
    document.getElementById("entry-form").addEventListener("submit", async (e) => {
      e.preventDefault();
      const name = document.getElementById("entry-name").value.trim();
      const email = document.getElementById("entry-email").value.trim();
      const experience = document.getElementById("entry-experience").value;
      const practiceAreas = Array.from(document.querySelectorAll('input[name="practice_area"]:checked')).map(
        (el) => el.value
      );

      let valid = true;
      toggleFieldError("entry-name-error", name.length === 0);
      if (name.length === 0) valid = false;
      const emailOk = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
      toggleFieldError("entry-email-error", !emailOk);
      if (!emailOk) valid = false;
      toggleFieldError("entry-experience-error", experience === "");
      if (experience === "") valid = false;
      toggleFieldError("entry-practice-error", practiceAreas.length === 0);
      if (practiceAreas.length === 0) valid = false;
      if (!valid) return;

      if (!state) state = S.createInitialState();
      state.reviewer = { entry_completed: true, name, email, experience, practice_areas: practiceAreas };
      if (!state.session.started_at) state.session.started_at = new Date().toISOString();
      persistState(true);

      await proceedToDataLoad();
    });
  }

  function toggleFieldError(id, show) {
    document.getElementById(id).classList.toggle("show", show);
  }

  // ---------------------------------------------------------------------
  // Cross-device resume — looks up an in-progress review_sessions row in
  // Supabase by email (see supabase_client.js), so a lawyer who started
  // on one device/browser can continue on another. No-ops entirely (the
  // whole UI block stays hidden) when remote storage isn't configured.
  // ---------------------------------------------------------------------
  let _lastAutoCheckedEmail = null;

  function wireResumeSession() {
    const wrap = document.getElementById("resume-session-wrap");
    if (!window.LegalSupabase || !window.LegalSupabase.isConfigured()) {
      wrap.classList.add("hidden");
      return;
    }
    wrap.classList.remove("hidden");

    const checkBtn = document.getElementById("resume-check-btn");
    checkBtn.addEventListener("click", () => checkForSavedProgress({ silent: false }));

    // "Sign-in"-like behavior: as soon as the lawyer finishes typing a
    // valid email and moves on, silently check whether they have saved
    // progress, so returning reviewers are recognized automatically
    // instead of needing to remember to click the button themselves. Only
    // speaks up when something is actually found — stays silent on
    // invalid/not-found so it doesn't nag while the form is mid-fill.
    document.getElementById("entry-email").addEventListener("blur", () => checkForSavedProgress({ silent: true }));
  }

  async function checkForSavedProgress(opts) {
    const silent = opts && opts.silent;
    const email = document.getElementById("entry-email").value.trim();
    const checkBtn = document.getElementById("resume-check-btn");
    const resultEl = document.getElementById("resume-result");

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      if (!silent) {
        resultEl.textContent = "Enter a valid email above first, then check again.";
        resultEl.classList.remove("hidden");
      }
      return;
    }
    if (silent && email === _lastAutoCheckedEmail) return; // avoid re-checking the same email on every blur
    if (silent) _lastAutoCheckedEmail = email;

    if (!silent) {
      checkBtn.disabled = true;
      checkBtn.textContent = "Checking…";
    }
    const result = await window.LegalSupabase.loadSessionRemote(email);
    if (!silent) {
      checkBtn.disabled = false;
      checkBtn.textContent = "Check for Saved Progress";
    }

    if (!result.ok) {
      if (!silent) {
        resultEl.textContent = "Could not check for saved progress: " + result.error;
        resultEl.classList.remove("hidden");
      }
      return;
    }
    if (!result.found) {
      if (!silent) {
        resultEl.textContent = "No saved progress found for this email.";
        resultEl.classList.remove("hidden");
      }
      return;
    }

    const completedCount = S.getCompletionSummary(result.state).completedCount;
    const total = result.state.scenarios.length;
    resultEl.innerHTML = "";
    resultEl.classList.remove("hidden");
    const p = document.createElement("p");
    p.textContent = `Welcome back — found saved progress (${completedCount}/${total} scenarios complete, last saved ${new Date(result.updatedAt).toLocaleString()}).`;
    const resumeBtn = document.createElement("button");
    resumeBtn.type = "button";
    resumeBtn.className = "btn btn-primary";
    resumeBtn.textContent = "Resume This Session";
    resumeBtn.addEventListener("click", async () => {
      state = result.state;
      S.saveStateNow(state);
      await routeFromState(true);
    });
    const startFreshBtn = document.createElement("button");
    startFreshBtn.type = "button";
    startFreshBtn.className = "btn-text";
    startFreshBtn.textContent = "Start fresh instead";
    startFreshBtn.addEventListener("click", () => {
      resultEl.classList.add("hidden");
      resultEl.innerHTML = "";
    });
    resultEl.appendChild(p);
    resultEl.appendChild(resumeBtn);
    resultEl.appendChild(startFreshBtn);
  }

  // ---------------------------------------------------------------------
  // Data loading (default mode: bundled fetch, with manual fallback)
  // ---------------------------------------------------------------------
  async function proceedToDataLoad() {
    if (state.scenario_source.loaded && state.scenarios.length > 0) {
      showScreen("review");
      renderReviewScreen(true);
      return;
    }
    showScreen("loading");
    const remoteScenarios = await I.loadScenariosFromSupabase();
    if (remoteScenarios && remoteScenarios.length > 0) {
      commitScenarios(remoteScenarios, "supabase");
      showScreen("review");
      renderReviewScreen(false);
      return;
    }
    const scenarios = await I.loadBundledSampleData();
    if (scenarios && scenarios.length > 0) {
      commitScenarios(scenarios, "bundled");
      showScreen("review");
      renderReviewScreen(false);
    } else {
      showScreen("manual-fallback-import");
    }
  }

  function commitScenarios(scenarios, origin) {
    state.scenarios = scenarios;
    const summary = I.summarizeScenarios(scenarios);
    state.scenario_source = {
      loaded: true,
      origin,
      scenario_count: summary.count,
      models_seen: summary.modelsSeen,
      index_range: summary.indexRange,
    };
    state.current_scenario_pos = 0;
    persistState(true);
  }

  // ---------------------------------------------------------------------
  // Dropzones (shared by fallback + researcher import)
  // ---------------------------------------------------------------------
  function wireDropzone(dropzoneId, inputId, chooseBtnId, onFiles) {
    const dropzone = document.getElementById(dropzoneId);
    const input = document.getElementById(inputId);
    const chooseBtn = document.getElementById(chooseBtnId);

    chooseBtn.addEventListener("click", () => input.click());
    input.addEventListener("change", () => {
      if (input.files && input.files.length) onFiles(Array.from(input.files));
      input.value = "";
    });
    dropzone.addEventListener("dragover", (e) => {
      e.preventDefault();
      dropzone.classList.add("dragover");
    });
    dropzone.addEventListener("dragleave", () => dropzone.classList.remove("dragover"));
    dropzone.addEventListener("drop", (e) => {
      e.preventDefault();
      dropzone.classList.remove("dragover");
      if (e.dataTransfer.files && e.dataTransfer.files.length) onFiles(Array.from(e.dataTransfer.files));
    });
  }

  async function readFilesAsRawInputs(files) {
    const rawInputs = [];
    const readErrors = [];
    for (const file of files) {
      try {
        const parsedJson = await I.readFileAsJSON(file);
        rawInputs.push({ filename: file.name, parsedJson });
      } catch (e) {
        readErrors.push(e.message);
      }
    }
    return { rawInputs, readErrors };
  }

  async function handleFallbackFiles(files) {
    const { rawInputs, readErrors } = await readFilesAsRawInputs(files);
    const { scenarios, warnings, errors } = I.mergeScenarioSources(rawInputs);
    const allErrors = readErrors.concat(errors);
    renderImportMessages("fallback-errors", allErrors, "fallback-warnings", warnings);
    if (scenarios.length > 0) {
      commitScenarios(scenarios, "manual_fallback_import");
      showScreen("review");
      renderReviewScreen(false);
    }
  }

  async function handleResearcherFiles(files) {
    const { rawInputs, readErrors } = await readFilesAsRawInputs(files);
    const { scenarios, warnings, errors } = I.mergeScenarioSources(rawInputs);
    const allErrors = readErrors.concat(errors);
    renderImportMessages("researcher-errors", allErrors, "researcher-warnings", warnings);

    const summaryEl = document.getElementById("researcher-summary");
    const actionsEl = document.getElementById("researcher-actions");
    if (scenarios.length > 0) {
      pendingResearcherScenarios = scenarios;
      const summary = I.summarizeScenarios(scenarios);
      summaryEl.classList.remove("hidden");
      summaryEl.innerHTML = `
        <strong>${summary.count} scenario${summary.count === 1 ? "" : "s"} successfully loaded</strong><br/>
        Model${summary.modelsSeen.length === 1 ? "" : "s"}: ${escapeHtml(summary.modelsSeen.join(", ") || "unknown")}<br/>
        Scenarios: ${summary.indexRange[0]}–${summary.indexRange[1]}
      `;
      actionsEl.classList.remove("hidden");
    } else {
      summaryEl.classList.add("hidden");
      actionsEl.classList.add("hidden");
      pendingResearcherScenarios = null;
    }
  }

  function renderImportMessages(errorsId, errors, warningsId, warnings) {
    const errorsEl = document.getElementById(errorsId);
    const warningsEl = document.getElementById(warningsId);
    if (errors.length > 0) {
      errorsEl.classList.remove("hidden");
      errorsEl.innerHTML = `<strong>Unable to load ${errors.length} item${errors.length === 1 ? "" : "s"}:</strong><ul>${errors
        .map((e) => `<li>${escapeHtml(e)}</li>`)
        .join("")}</ul>`;
    } else {
      errorsEl.classList.add("hidden");
      errorsEl.innerHTML = "";
    }
    if (warnings.length > 0) {
      warningsEl.classList.remove("hidden");
      warningsEl.innerHTML = `<ul>${warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join("")}</ul>`;
    } else {
      warningsEl.classList.add("hidden");
      warningsEl.innerHTML = "";
    }
  }

  function wireStaticButtons() {
    // Bound exactly once — see the comment on onActCardClick/onActCardChange
    // for why this must not be repeated inside renderActCards.
    const actCardsContainer = document.getElementById("act-cards-container");
    actCardsContainer.addEventListener("click", onActCardClick);
    actCardsContainer.addEventListener("change", onActCardChange);

    document.getElementById("researcher-start-review-btn").addEventListener("click", () => {
      if (!pendingResearcherScenarios) return;
      if (!state) state = S.createInitialState();
      commitScenarios(pendingResearcherScenarios, "researcher_import");
      if (!state.reviewer.entry_completed) {
        showScreen("lawyer-entry");
      } else {
        showScreen("review");
        renderReviewScreen(false);
      }
    });

    document.getElementById("researcher-download-merged-btn").addEventListener("click", () => {
      if (!pendingResearcherScenarios) return;
      const stripped = pendingResearcherScenarios.map((s) => {
        const clone = Object.assign({}, s);
        delete clone._parsed;
        return clone;
      });
      E.downloadJSON(stripped, "sample_results.json");
    });

    document.getElementById("review-prev-btn").addEventListener("click", () => {
      if (state.current_scenario_pos > 0) {
        state.current_scenario_pos--;
        persistState(false);
        renderReviewScreen(false);
      }
    });

    document.getElementById("review-save-draft-btn").addEventListener("click", async () => {
      const btn = document.getElementById("review-save-draft-btn");
      btn.disabled = true;
      const originalLabel = btn.textContent;
      btn.textContent = "Saving…";
      const remoteResult = await persistState(true);
      btn.disabled = false;
      btn.textContent = originalLabel;

      if (remoteResult.skipped) {
        showToast("Progress saved on this device.");
      } else if (remoteResult.ok) {
        showToast("Progress saved — you can safely close this and resume later with your email.");
      } else {
        showToast("Saved on this device, but couldn't sync remotely (will retry automatically): " + remoteResult.error);
      }
    });

    document.getElementById("review-save-next-btn").addEventListener("click", () => {
      persistState(true);
      if (state.current_scenario_pos < state.scenarios.length - 1) {
        state.current_scenario_pos++;
        persistState(false);
        renderReviewScreen(false);
      } else {
        showScreen("completion");
        renderCompletionScreen();
      }
    });

    document.getElementById("nav-dropdown-select").addEventListener("change", (e) => {
      const pos = Number(e.target.value);
      if (!Number.isNaN(pos)) {
        state.current_scenario_pos = pos;
        persistState(false);
        renderReviewScreen(false);
      }
    });

    document.getElementById("completion-review-btn").addEventListener("click", () => {
      showScreen("review");
      renderReviewScreen(false);
    });

    document.getElementById("completion-submit-btn").addEventListener("click", () => {
      document.getElementById("submit-confirm-checkbox").checked = false;
      document.getElementById("submit-modal-confirm-btn").disabled = true;
      document.getElementById("submit-modal").classList.add("active");
    });

    document.getElementById("submit-modal-cancel-btn").addEventListener("click", () => {
      document.getElementById("submit-modal").classList.remove("active");
    });

    document.getElementById("submit-confirm-checkbox").addEventListener("change", (e) => {
      document.getElementById("submit-modal-confirm-btn").disabled = !e.target.checked;
    });

    document.getElementById("submit-modal-confirm-btn").addEventListener("click", handleSubmit);

    document.getElementById("post-submit-download-btn").addEventListener("click", () => {
      const payload = E.buildExportPayload(state);
      E.downloadJSON(payload, E.buildFilename(state.reviewer.name, new Date(state.submitted_at)));
    });
    document.getElementById("post-submit-download-pdf-btn").addEventListener("click", () => {
      const payload = E.buildExportPayload(state);
      window.LegalPdfReport.downloadSubmissionPdf(
        payload,
        E.buildFilename(state.reviewer.name, new Date(state.submitted_at)).replace(/\.json$/, ".pdf")
      );
    });
  }

  // When remote storage is configured and the submission saves there
  // successfully, the lawyer does NOT get a local download of their own —
  // the data lives centrally and only an admin can retrieve it (see
  // js/admin.js). Local JSON+PDF download is kept ONLY as a fallback for
  // when remote storage is absent or the submit call fails, so a
  // completed review is never silently lost.
  async function handleSubmit() {
    state.submitted_at = new Date().toISOString();
    const payload = E.buildExportPayload(state);
    const filename = E.buildFilename(state.reviewer.name, new Date(state.submitted_at));

    const remoteResult = await E.submitToRemoteDatabase(payload);
    persistState(true);

    document.getElementById("submit-modal").classList.remove("active");
    renderCompletionScreen();

    const remoteSucceeded = remoteResult.ok && !remoteResult.skipped;
    if (remoteSucceeded) {
      if (window.LegalSupabase) window.LegalSupabase.deleteSessionRemote(state.reviewer.email);
      showPostSubmitPanel({ localDownload: false });
      showToast("Submitted securely. Thank you.");
    } else {
      E.downloadJSON(payload, filename);
      window.LegalPdfReport.downloadSubmissionPdf(payload, filename.replace(/\.json$/, ".pdf"));
      showPostSubmitPanel({ localDownload: true });
      if (!remoteResult.ok) {
        showToast("Saved locally (remote submission failed: " + remoteResult.error + ")");
      }
    }
  }

  function showPostSubmitPanel(opts) {
    document.getElementById("post-submit-panel").classList.remove("hidden");
    document.getElementById("completion-actions").classList.add("hidden");
    const localDownload = opts ? opts.localDownload : !(window.LegalSupabase && window.LegalSupabase.isConfigured());
    document.getElementById("post-submit-download-btn").classList.toggle("hidden", !localDownload);
    document.getElementById("post-submit-download-pdf-btn").classList.toggle("hidden", !localDownload);
    document.getElementById("post-submit-note").textContent = localDownload
      ? "A copy has been downloaded to your device as a backup. You may close this window."
      : "Your evaluation has been securely submitted and saved. You may close this window.";
  }

  // ---------------------------------------------------------------------
  // Review screen
  // ---------------------------------------------------------------------
  function currentScenario() {
    return state.scenarios[state.current_scenario_pos];
  }

  function ensureProgressEntry(scenario) {
    const key = String(scenario.scenario_index);
    if (!state.progress[key]) {
      state.progress[key] = S.createScenarioProgress(Object.keys(scenario.answers));
    }
    return state.progress[key];
  }

  function renderReviewScreen(showRestoredNote) {
    const scenario = currentScenario();
    if (!scenario) return;
    ensureProgressEntry(scenario);

    const total = state.scenarios.length;
    const pos = state.current_scenario_pos;
    document.getElementById("review-scenario-heading").textContent = `Scenario ${pos + 1} of ${total}`;
    const pct = Math.round(((pos + 1) / total) * 100);
    document.getElementById("review-progress-pct").textContent = `${pct}%`;
    document.getElementById("review-progress-fill").style.width = `${pct}%`;

    const banner = document.getElementById("researcher-banner");
    if (IS_RESEARCHER) {
      banner.classList.remove("hidden");
      banner.textContent = `Researcher mode — model: ${scenario.model || "unknown"} — generated ${scenario.generated_at || "unknown"}`;
    } else {
      banner.classList.add("hidden");
    }

    renderNav();

    let questionHtml = "";
    if (showRestoredNote) {
      questionHtml += `<p class="progress-restored-note">Your progress from a previous session has been restored.</p>`;
    }
    document.getElementById("review-question-text").textContent = scenario.question;
    const restoredNoteHolder = document.getElementById("review-question-text").parentElement;
    const existingNote = restoredNoteHolder.querySelector(".progress-restored-note");
    if (existingNote) existingNote.remove();
    if (showRestoredNote) {
      restoredNoteHolder.insertAdjacentHTML("afterbegin", questionHtml);
    }

    renderActCards(scenario);
    renderScenarioQuestionsPanel(scenario);
    renderSynthesisPanel(scenario);

    document.getElementById("review-prev-btn").disabled = pos === 0;
    document.getElementById("review-save-next-btn").textContent = pos === total - 1 ? "Save & Finish" : "Save & Next";
  }

  function renderNav() {
    const scenarios = state.scenarios;
    const pos = state.current_scenario_pos;

    const listHtml = scenarios
      .map((s, i) => {
        const complete = S.isScenarioComplete(state, s.scenario_index);
        const isCurrent = i === pos;
        let mark = "";
        if (isCurrent) mark = '<span class="nav-mark current">●</span>';
        else if (complete) mark = '<span class="nav-mark done">✓</span>';
        return `<button type="button" class="nav-item${isCurrent ? " current" : ""}" data-nav-pos="${i}">
          <span>Scenario ${i + 1}</span>${mark}
        </button>`;
      })
      .join("");
    const sidebarList = document.getElementById("nav-sidebar-list");
    sidebarList.innerHTML = listHtml;
    sidebarList.querySelectorAll("[data-nav-pos]").forEach((btn) => {
      btn.addEventListener("click", () => {
        state.current_scenario_pos = Number(btn.getAttribute("data-nav-pos"));
        persistState(false);
        renderReviewScreen(false);
      });
    });

    const select = document.getElementById("nav-dropdown-select");
    select.innerHTML = scenarios
      .map((s, i) => {
        const complete = S.isScenarioComplete(state, s.scenario_index);
        const mark = i === pos ? " (current)" : complete ? " ✓" : "";
        return `<option value="${i}" ${i === pos ? "selected" : ""}>Scenario ${i + 1}${mark}</option>`;
      })
      .join("");
  }

  // ---------------------------------------------------------------------
  // Act cards
  // ---------------------------------------------------------------------
  function renderMarkdown(text) {
    const html = window.marked.parse(text || "");
    return window.DOMPurify.sanitize(html);
  }

  function renderActCards(scenario) {
    const container = document.getElementById("act-cards-container");
    const progress = ensureProgressEntry(scenario);
    const actNames = Object.keys(scenario.answers);

    container.innerHTML = actNames.map((actName) => renderActCard(scenario, progress, actName)).join("");

    // Fresh child nodes each render get fresh per-element listeners here
    // (old nodes + their listeners are discarded together by innerHTML
    // replacement, so this is safe to redo every render).
    container.querySelectorAll('[data-add-provision-form] select[data-role="provision-act-select"]').forEach((sel) => {
      sel.addEventListener("change", () => {
        const otherInput = sel.parentElement.querySelector('[data-role="provision-other-act"]');
        otherInput.classList.toggle("hidden", sel.value !== "Other");
      });
    });
  }

  function shortActLabel(actName) {
    return actName.split(",")[0].split("(")[0].trim();
  }

  function renderActCard(scenario, progress, actName) {
    const parsed = scenario._parsed[actName];
    const review = progress.lawyer_validation.act_reviews[actName];
    const rawAnswer = scenario.answers[actName];
    const explanationId = `explanation-${scenario.scenario_index}-${slugForId(actName)}`;

    let body;
    if (parsed.is_no_answer) {
      body = renderNoAnswerBody(actName, review);
    } else {
      body = renderSectionedBody(actName, parsed, review, explanationId, rawAnswer);
    }

    return `
      <div class="card act-card" data-act="${escapeAttr(actName)}">
        <div style="display:flex; justify-content:space-between; align-items:baseline; flex-wrap:wrap; gap: var(--space-2);">
          <h3 style="margin-bottom:0;">${escapeHtml(shortActLabel(actName))}</h3>
          ${renderActPdfLink(scenario.scenario_index, actName)}
        </div>
        ${body}
      </div>
    `;
  }

  function renderNoAnswerBody(actName, review) {
    const addPanel = renderAddProvisionPanel(actName, "no-answer");
    return `
      <div class="no-answer-banner">System did not identify an applicable provision under this Act.</div>
      <div class="sub-question">
        <h4>Is that assessment correct?</h4>
        ${choiceRow("set-no-answer-assessment", actName, null, [
          ["yes", "Yes", "neutral"],
          ["no", "No", "negative"],
          ["unsure", "Unsure", "unsure"],
        ], review.no_answer_assessment)}
        <div class="${review.no_answer_assessment === "no" ? "" : "hidden"}" data-no-answer-add-wrap="${escapeAttr(actName)}">
          <p class="muted">Add the Act and Section that should apply:</p>
          ${addPanel}
        </div>
      </div>
    `;
  }

  function renderSectionedBody(actName, parsed, review, explanationId, rawAnswer) {
    const chips =
      parsed.extracted_sections.length > 0
        ? `<div class="chip-row">${parsed.extracted_sections.map((s) => `<span class="chip">${escapeHtml(s)}</span>`).join("")}</div>`
        : `<p class="muted">No specific sections auto-detected in this Act's answer.</p>`;

    const applicabilityRow = choiceRow(
      "set-act-applicability",
      actName,
      null,
      [
        ["applicable", "✅ Applicable", "positive"],
        ["partially_applicable", "⚠️ Partially Applicable", "partial"],
        ["not_applicable", "❌ Not Applicable", "negative"],
        ["unsure", "❓ Unsure", "unsure"],
      ],
      review.applicability
    );

    const sectionRows = parsed.extracted_sections
      .map((section) => {
        const value = review.sections[section] || null;
        return `
        <div class="section-row">
          <span class="section-name">${escapeHtml(section)}</span>
          ${choiceRow("set-section-verdict", actName, section, [
            ["applicable", "Applicable", "positive"],
            ["not_applicable", "Not Applicable", "negative"],
            ["unsure", "Unsure", "unsure"],
          ], value)}
        </div>`;
      })
      .join("");

    const missingBlock = `
      <div class="sub-question">
        <h4>Is any important applicable Section missing from the system recommendation?</h4>
        ${choiceRow("set-missing-flag", actName, null, [
          ["no", "No", "neutral"],
          ["yes", "Yes", "negative"],
          ["unsure", "Unsure", "unsure"],
        ], review.missing_flag)}
        <div class="${review.missing_flag === "yes" ? "" : "hidden"}" data-missing-add-wrap="${escapeAttr(actName)}">
          ${renderAddProvisionPanel(actName, "missing")}
          ${renderMissingProvisionChips(actName)}
        </div>
      </div>
    `;

    const irrelevantOptions = parsed.extracted_sections
      .map(
        (section) => `
        <label class="checkbox-row">
          <input type="checkbox" data-action="toggle-irrelevant-section" data-act="${escapeAttr(actName)}" data-section="${escapeAttr(section)}" ${review.irrelevant_sections_checked.includes(section) ? "checked" : ""} />
          ${escapeHtml(section)}
        </label>`
      )
      .join("");

    const irrelevantBlock = `
      <div class="sub-question">
        <h4>Has the system included any provision that should not apply?</h4>
        ${choiceRow("set-irrelevant-flag", actName, null, [
          ["no", "No", "neutral"],
          ["yes", "Yes", "negative"],
          ["unsure", "Unsure", "unsure"],
        ], review.irrelevant_flag)}
        <div class="checkbox-list ${review.irrelevant_flag === "yes" ? "" : "hidden"}" data-irrelevant-wrap="${escapeAttr(actName)}">
          ${irrelevantOptions || '<p class="muted">No auto-detected sections to flag.</p>'}
        </div>
      </div>
    `;

    return `
      ${chips}
      <div class="sub-question" style="border-top:none; padding-top:0; margin-top:0;">
        <h4>Is this Act applicable to the scenario?</h4>
        ${applicabilityRow}
      </div>
      ${sectionRows}
      <button type="button" class="btn-text" data-action="toggle-explanation" data-target="${explanationId}">
        ${openExplanationIds.has(explanationId) ? "Hide System Explanation" : "View System Explanation"}
      </button>
      <div class="explanation-panel${openExplanationIds.has(explanationId) ? "" : " hidden"}" id="${explanationId}">${renderMarkdown(rawAnswer)}</div>
      ${missingBlock}
      ${irrelevantBlock}
    `;
  }

  function renderAddProvisionPanel(actName, mode) {
    // Pre-selects the Act this panel is rendered inside of, so a lawyer
    // adding a missing/no-answer provision without touching the dropdown
    // gets it attributed to the Act they're actually reviewing, not
    // silently defaulted to whichever Act happens to be first in the list.
    const actOptions = I.REQUIRED_ACT_KEYS.concat(["Other"])
      .map((a) => `<option value="${escapeAttr(a)}"${a === actName ? " selected" : ""}>${escapeHtml(shortActLabel(a))}</option>`)
      .join("");
    return `
      <div class="inline-form-row" data-add-provision-form data-act="${escapeAttr(actName)}" data-mode="${mode}">
        <select data-role="provision-act-select">${actOptions}</select>
        <input type="text" data-role="provision-other-act" class="hidden" placeholder="Specify Act name" />
        <input type="text" data-role="provision-section" placeholder="e.g. Section 318" />
        <button type="button" class="btn" data-action="add-missing-provision" data-act="${escapeAttr(actName)}">+ Add Provision</button>
      </div>
    `;
  }

  function renderMissingProvisionChips(forAct) {
    const key = String(currentScenario().scenario_index);
    const list = state.progress[key].lawyer_validation.missing_provisions;
    const relevant = list.map((p, i) => ({ ...p, i })).filter((p) => p.act === forAct);
    if (relevant.length === 0) return "";
    return `<div class="chip-row">${relevant
      .map(
        (p) => `<span class="chip chip-added">${escapeHtml(p.act)} — ${escapeHtml(p.section)}
          <button type="button" class="btn-text" style="padding:0 0 0 6px;" data-action="remove-missing-provision" data-index="${p.i}" aria-label="Remove">×</button>
        </span>`
      )
      .join("")}</div>`;
  }

  function choiceRow(action, actName, section, options, selectedValue) {
    return `<div class="choice-row">${options
      .map(([value, label, tone]) => {
        const selected = value === selectedValue;
        return `<button type="button" class="choice-btn${selected ? " selected" : ""}" data-tone="${tone}"
          data-action="${action}" data-act="${escapeAttr(actName)}"
          ${section !== null ? `data-section="${escapeAttr(section)}"` : ""}
          data-value="${value}">${label}</button>`;
      })
      .join("")}</div>`;
  }

  // Bound exactly once (in wireStaticButtons) on the persistent
  // #act-cards-container — never re-bound per render, since only its
  // *children* are replaced by renderActCards, not the container itself.
  // scenario/progress are looked up fresh at click time so this stays
  // correct across scenario navigation.
  function onActCardClick(e) {
    const scenario = currentScenario();
    if (!scenario) return;
    const btn = e.target.closest("[data-action]");
    if (!btn) return;
    const action = btn.getAttribute("data-action");
    const act = btn.getAttribute("data-act");

    if (action === "toggle-explanation") {
      const targetId = btn.getAttribute("data-target");
      const panel = document.getElementById(targetId);
      const nowHidden = panel.classList.toggle("hidden");
      btn.textContent = nowHidden ? "View System Explanation" : "Hide System Explanation";
      if (nowHidden) openExplanationIds.delete(targetId);
      else openExplanationIds.add(targetId);
      return;
    }

    if (action === "set-act-applicability") {
      const value = btn.getAttribute("data-value");
      mutateScenarioProgress(scenario, (lv) => {
        lv.act_reviews[act].applicability = value;
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "set-section-verdict") {
      const section = btn.getAttribute("data-section");
      const value = btn.getAttribute("data-value");
      mutateScenarioProgress(scenario, (lv) => {
        lv.act_reviews[act].sections[section] = value;
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "set-no-answer-assessment") {
      const value = btn.getAttribute("data-value");
      mutateScenarioProgress(scenario, (lv) => {
        lv.act_reviews[act].no_answer_assessment = value;
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "set-missing-flag") {
      const value = btn.getAttribute("data-value");
      mutateScenarioProgress(scenario, (lv) => {
        lv.act_reviews[act].missing_flag = value;
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "set-irrelevant-flag") {
      const value = btn.getAttribute("data-value");
      mutateScenarioProgress(scenario, (lv) => {
        lv.act_reviews[act].irrelevant_flag = value;
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "add-missing-provision") {
      const form = btn.closest("[data-add-provision-form]");
      const actSelect = form.querySelector('[data-role="provision-act-select"]');
      const otherInput = form.querySelector('[data-role="provision-other-act"]');
      const sectionInput = form.querySelector('[data-role="provision-section"]');
      const chosenAct = actSelect.value === "Other" ? otherInput.value.trim() || "Other" : actSelect.value;
      const section = sectionInput.value.trim();
      if (!section) {
        showToast("Please enter a Section before adding.");
        return;
      }
      mutateScenarioProgress(scenario, (lv) => {
        lv.missing_provisions.push({ act: chosenAct, section });
      });
      renderReviewScreen(false);
      return;
    }

    if (action === "remove-missing-provision") {
      const index = Number(btn.getAttribute("data-index"));
      mutateScenarioProgress(scenario, (lv) => {
        lv.missing_provisions.splice(index, 1);
      });
      renderReviewScreen(false);
      return;
    }
  }

  function onActCardChange(e) {
    const scenario = currentScenario();
    if (!scenario) return;
    const el = e.target;
    if (el.matches('[data-action="toggle-irrelevant-section"]')) {
      const act = el.getAttribute("data-act");
      const section = el.getAttribute("data-section");
      mutateScenarioProgress(scenario, (lv) => {
        const review = lv.act_reviews[act];
        const idx = review.irrelevant_sections_checked.indexOf(section);
        if (el.checked && idx === -1) review.irrelevant_sections_checked.push(section);
        if (!el.checked && idx !== -1) review.irrelevant_sections_checked.splice(idx, 1);
        recomputeIrrelevantProvisions(lv);
      });
      renderReviewScreen(false);
    }
  }

  function recomputeIrrelevantProvisions(lv) {
    lv.irrelevant_provisions = [];
    for (const [act, review] of Object.entries(lv.act_reviews)) {
      for (const section of review.irrelevant_sections_checked) {
        lv.irrelevant_provisions.push({ act, section });
      }
    }
  }

  function mutateScenarioProgress(scenario, patchFn) {
    S.patchScenarioProgress(state, scenario.scenario_index, Object.keys(scenario.answers), patchFn);
    persistState(false);
  }

  // ---------------------------------------------------------------------
  // Scenario-level questions panel
  // ---------------------------------------------------------------------
  function renderScenarioQuestionsPanel(scenario) {
    const progress = ensureProgressEntry(scenario);
    const lv = progress.lawyer_validation;
    const panel = document.getElementById("scenario-questions-panel");

    panel.innerHTML = `
      <div class="sub-question" style="margin-top:0; padding-top:0; border-top:none;">
        <h4>Overall, how legally accurate is the system recommendation?</h4>
        ${ratingRow("set-overall-correctness", CORRECTNESS_LABELS, lv.overall_correctness)}
      </div>
      <div class="sub-question">
        <h4>How confident are you in your assessment?</h4>
        ${ratingRow("set-confidence", CONFIDENCE_LABELS, lv.confidence)}
      </div>
      <div class="sub-question">
        <h4>Does the scenario contain enough facts to determine the applicable provisions?</h4>
        ${choiceRow("set-factual-sufficiency", "", null, [
          ["yes", "✅ Yes", "neutral"],
          ["partially", "⚠️ Partially", "partial"],
          ["no", "❌ No", "negative"],
        ], lv.factual_sufficiency)}
      </div>
      <div class="sub-question">
        <h4>Could another reasonable lawyer reach a different conclusion regarding the applicable Sections?</h4>
        ${choiceRow("set-multiple-interpretations", "", null, [
          ["yes", "Yes", "neutral"],
          ["no", "No", "neutral"],
          ["unsure", "Unsure", "unsure"],
        ], lv.multiple_interpretations)}
        <div class="${lv.multiple_interpretations === "yes" ? "" : "hidden"}" data-ambiguity-wrap>
          <label for="ambiguity-comment-input">Reason for possible alternative interpretation (optional)</label>
          <textarea id="ambiguity-comment-input" data-role="ambiguity-comment">${escapeHtml(lv.ambiguity_comment || "")}</textarea>
        </div>
      </div>
      <div class="sub-question">
        <h4>Additional Legal Comments (optional)</h4>
        <textarea id="comments-input" data-role="comments" placeholder="Mention any missing provision, incorrect interpretation, exception, qualification or factual assumption.">${escapeHtml(lv.comments || "")}</textarea>
      </div>
    `;

    panel.querySelectorAll("[data-action]").forEach((btn) => {
      btn.addEventListener("click", () => {
        const action = btn.getAttribute("data-action");
        const value = btn.getAttribute("data-value");
        mutateScenarioProgress(scenario, (lvInner) => {
          if (action === "set-overall-correctness") lvInner.overall_correctness = Number(value);
          if (action === "set-confidence") lvInner.confidence = Number(value);
          if (action === "set-factual-sufficiency") lvInner.factual_sufficiency = value;
          if (action === "set-multiple-interpretations") lvInner.multiple_interpretations = value;
        });
        renderReviewScreen(false);
      });
    });

    bindDebouncedTextarea(panel.querySelector('[data-role="ambiguity-comment"]'), scenario, (lvInner, val) => {
      lvInner.ambiguity_comment = val;
    });
    bindDebouncedTextarea(panel.querySelector('[data-role="comments"]'), scenario, (lvInner, val) => {
      lvInner.comments = val;
    });
  }

  // Bound directly (not via delegated re-render) so typing never loses
  // focus/cursor position.
  function bindDebouncedTextarea(el, scenario, applyFn) {
    if (!el) return;
    el.addEventListener("input", () => {
      mutateScenarioProgress(scenario, (lv) => applyFn(lv, el.value));
    });
  }

  function ratingRow(action, labels, selectedValue) {
    return `<div class="rating-row">${[1, 2, 3, 4, 5]
      .map(
        (n) => `<button type="button" class="rating-btn${n === selectedValue ? " selected" : ""}" data-action="${action}" data-value="${n}">
          <span class="rating-num">${n}</span><span class="rating-label">${labels[n]}</span>
        </button>`
      )
      .join("")}</div>`;
  }

  function renderSynthesisPanel(scenario) {
    const pdfLink = `<a class="btn-text" href="${escapeAttr(scenarioPdfUrl(scenario.scenario_index, "AllActs.pdf"))}" target="_blank" rel="noopener">Download Original Combined PDF ↓</a>`;
    document.getElementById("synthesis-content").innerHTML = `<div style="margin-bottom: var(--space-3);">${pdfLink}</div>` + renderMarkdown(scenario.synthesis || "");
  }

  // ---------------------------------------------------------------------
  // Completion screen
  // ---------------------------------------------------------------------
  function renderCompletionScreen() {
    const summary = S.getCompletionSummary(state);
    document.getElementById("completion-reviewer-line").textContent = `Reviewer: ${state.reviewer.name}`;
    document.getElementById("completion-count-line").textContent = `Completed: ${summary.completedCount} / ${summary.total} scenarios`;

    const body = document.getElementById("completion-summary-body");
    body.innerHTML = state.scenarios
      .map((s) => {
        const entry = state.progress[String(s.scenario_index)];
        const lv = entry ? entry.lawyer_validation : null;
        const correctness = lv && lv.overall_correctness ? CORRECTNESS_LABELS[lv.overall_correctness] : "—";
        const confidence = lv && lv.confidence ? CONFIDENCE_LABELS[lv.confidence] : "—";
        return `<tr><td>${s.scenario_index}</td><td>${escapeHtml(correctness)}</td><td>${escapeHtml(confidence)}</td></tr>`;
      })
      .join("");

    if (!state.submitted_at) {
      document.getElementById("post-submit-panel").classList.add("hidden");
      document.getElementById("completion-actions").classList.remove("hidden");
    }
  }

  // ---------------------------------------------------------------------
  // Utilities
  // ---------------------------------------------------------------------
  let toastTimer = null;
  function showToast(message) {
    const el = document.getElementById("error-toast");
    el.textContent = message;
    el.classList.add("show");
    if (toastTimer) clearTimeout(toastTimer);
    toastTimer = setTimeout(() => el.classList.remove("show"), 4000);
  }

  function escapeHtml(str) {
    return String(str == null ? "" : str).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  }
  function escapeAttr(str) {
    return escapeHtml(str);
  }
  function slugForId(str) {
    return String(str).toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  }
})();
